# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: caterpillar
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Install checkov
        run: pip install -U checkov

      - name: Get all policies from Prisma
        run: |
          env | sort
          echo "All available checks"
          checkov -l --output-bc-ids > ./all_policies.txt
      
      - name: Get filtered policies from Prisma
        run: |
          echo "Filtered checks by compliance standard"
          checkov -l --output-bc-ids --policy-metadata-filter policy.complianceStandard="ACSC Information Security Manual (ISM)" > ./filtered_policies.txt
